//
//  LACMutablePatch.h
//  Lacqit
//
//  Created by Pauli Ojala on 31.8.2008.
//  Copyright 2008 Lacquer oy/ltd. All rights reserved.
//

#import "LACPatch.h"
#import "LACDataMethods.h"


LACQIT_EXPORT_VAR NSString * const kLACNodeInterfaceHasChanged;  // sent as direct notif key on interface changes initiated by a node


@interface LACMutablePatch : LACPatch {
    
    NSMutableArray *_nodeObservers;
    
    // state during connection change grouping
    id _interfaceChangeInitiator;    
    NSMutableSet *_modifiedNodes;
}

- (void)setName:(NSString *)name;

- (void)addInputBindingWithType:(NSString *)type forKey:(NSString *)key;

- (void)setOutputBinding:(id)output forKey:(NSString *)key;

- (void)addNode:(id)node;
- (void)deleteNode:(id)node;
- (void)detachNodesFromTree:(NSSet *)nodeSet;

- (void)sortNodesRecursivelyFromPublishedOutputs;

- (void)applyNodeConnectionsByTagPlist:(NSDictionary *)info;  // applies connections in plist format (generated by -[LACPatch nodeConnectionsByTagPlist])

- (void)addNodeObserver:(id)observer;
- (void)removeNodeObserver:(id)observer;

- (BOOL)isInsideInterfaceChangeGrouping;

- (void)setGlobalScaleFactor:(double)scale;
- (double)globalScaleFactor;

// --- parser support ---
- (void)parseInputBindingsFromArray:(NSArray *)props;
- (void)parseOutputBindingsFromArray:(NSArray *)props;

@end


@interface NSObject (LACMutablePatchNodeModificationObserver)

- (void)nodesWereModified:(NSSet *)nodes inPatch:(id)patch contextInfo:(NSDictionary *)info;

@end
